---
  ListeningCOMPort: COM1 
  OutgoingCOMPORT: COM12
  PushoverAPPKey: asdfghbkjdfhgsdaflkj
  PushoverRegularUserGroupKey: asdgnasjlkdghnbj
  PushoverAdminUserGroupKey: adsgfsadgasdfgasdfg
  AlertThreshold: 3