AlertThreshold: '3'
LCP: COM4
LCPB: '14400'
PushoverAPIKey: abcdefghijlkmnopqrstuvwxyzabcd
PushoverAdminUserGroupKey: abcdefghijlkmnopqrstuvwxyzabcd
PushoverRegularUserGroupKey: abcdefghijlkmnopqrstuvwxyzabcd
RCP: COM6
RCPB: '14400'
RelayEnabled: true